# Generated by Django 4.2.16 on 2024-09-29 11:27

from django.db import migrations, models
import django.db.models.deletion

def create_unassigned_class(apps, schema_editor):
    Class = apps.get_model('smartscoreapp', 'Class')
    Class.objects.get_or_create(name='Unassigned Class', description='Default class for unassigned exams')


class Migration(migrations.Migration):

    dependencies = [
        ('smartscoreapp', '0001_initial'),
    ]


    operations = [
        migrations.RunPython(create_unassigned_class),
    ]
    operations = [
        migrations.AlterField(
            model_name='exam',
            name='class_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='smartscoreapp.class'),
        ),
    ]
