# Generated by Django 4.2.14 on 2024-07-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartscoreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('first_name', 'last_name', 'middle_initial', 'assigned_class')},
        ),
        migrations.RemoveField(
            model_name='student',
            name='suffix',
        ),
    ]
