# Generated by Django 4.2.14 on 2024-07-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartscoreapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='correct_answer',
            new_name='answer',
        ),
    ]
