# Generated by Django 4.2.16 on 2024-10-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartscoreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testset',
            name='answer_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
