# Generated by Django 4.2.13 on 2024-08-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartscoreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('first_name', 'last_name', 'middle_initial', 'assigned_class', 'student_id')},
        ),
    ]
