# Generated by Django 4.2.14 on 2024-07-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartscoreapp', '0002_remove_exam_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='', editable=False, max_length=7, unique=True),
        ),
    ]
