# Generated by Django 4.2.16 on 2024-09-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartscoreapp', '0002_alter_exam_class_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testset',
            name='set_id',
        ),
        migrations.AddField(
            model_name='testset',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='test_sets', to='smartscoreapp.question'),
        ),
        migrations.AlterField(
            model_name='testset',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartscoreapp.exam'),
        ),
        migrations.AlterField(
            model_name='testset',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartscoreapp.student'),
        ),
    ]
