# Generated by Django 4.2.16 on 2024-09-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartscoreapp', '0003_remove_testset_set_id_testset_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testset',
            name='set_id',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
