# Generated by Django 4.2.7 on 2024-06-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartscoreapp', '0004_testset_remove_student_email_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
    ]
