# Generated by Django 4.2.16 on 2024-10-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartscoreapp', '0004_testset_set_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('first_name', 'last_name', 'middle_initial', 'assigned_class')},
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=12),
        ),
    ]
