# Generated by Django 4.2.7 on 2024-06-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartscoreapp', '0005_class_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_assigned',
            new_name='assigned_class',
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(),
        ),
    ]
