# Generated by Django 4.2.7 on 2024-06-30 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartscoreapp', '0006_rename_class_assigned_student_assigned_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testset',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_sets', to='smartscoreapp.exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testset',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_sets', to='smartscoreapp.student'),
            preserve_default=False,
        ),
    ]
