# Generated by Django 4.2.16 on 2024-10-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartscoreapp', '0006_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='student',
            name='short_id',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('first_name', 'last_name', 'middle_initial', 'assigned_class', 'short_id')},
        ),
    ]
