# Generated by Django 4.2.13 on 2024-07-03 22:05

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('smartscoreapp', '0007_exam_exam_id_student_gender_testset_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,  # assuming settings.AUTH_USER_MODEL is correctly set
                default=1,  # replace with the ID of the default user
            ),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
