# Generated by Django 4.2.14 on 2024-07-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartscoreapp', '0010_alter_question_correct_answer_alter_question_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_e',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D'), ('E', 'Option E')], max_length=1),
        ),
    ]
