# Generated by Django 4.2.14 on 2024-07-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartscoreapp', '0011_question_option_e_alter_question_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_a_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c_value',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d_value',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='question',
            name='option_e_value',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_e',
            field=models.CharField(max_length=255),
        ),
    ]
