# Generated by Django 4.2.14 on 2024-07-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartscoreapp', '0012_question_option_a_value_question_option_b_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(related_name='exams', to='smartscoreapp.question'),
        ),
    ]
