# Generated by Django 4.2.14 on 2024-07-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartscoreapp', '0013_exam_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testset',
            name='name',
        ),
        migrations.AddField(
            model_name='question',
            name='question_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testset',
            name='set_no',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
