# Generated by Django 4.2.14 on 2024-07-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartscoreapp', '0014_remove_testset_name_question_question_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_order',
            field=models.IntegerField(default=1),
        ),
    ]
