# Generated by Django 4.2.14 on 2024-07-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartscoreapp', '0015_alter_question_question_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_a_value',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_b_value',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_c_value',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_d_value',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_e_value',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D'), ('E', 'Option E')], max_length=1)),
                ('option_a_value', models.IntegerField(default=0)),
                ('option_b_value', models.IntegerField(default=1)),
                ('option_c_value', models.IntegerField(default=2)),
                ('option_d_value', models.IntegerField(default=3)),
                ('option_e_value', models.IntegerField(default=4)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='smartscoreapp.question')),
            ],
        ),
    ]
