# Generated by Django 4.2.14 on 2024-07-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartscoreapp', '0016_remove_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ExamSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sets', to='smartscoreapp.exam')),
                ('students', models.ManyToManyField(related_name='exam_sets', to='smartscoreapp.student')),
            ],
            options={
                'unique_together': {('exam', 'set_number')},
            },
        ),
    ]
