# Generated by Django 4.2.14 on 2024-07-20 16:33

from django.db import migrations, models
import smartscoreapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('smartscoreapp', '0017_student_student_id_examset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=smartscoreapp.models.generate_student_id, max_length=20, unique=True),
        ),
    ]
